# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: .vscode
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=120]

  # Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --ignore=E203, --ignore=W503]

  # isort
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  # Poetry
  -   repo: https://github.com/python-poetry/poetry
      rev: 1.8.3
      hooks:
      - id: poetry-check
        args: [-C, ./backend]
      - id: poetry-lock
        args: [-C, ./backend]
      - id: poetry-install
        args: [-C, ./backend]
      - id: poetry-export
        name: Export requirements.txt
        args: [-C, ./backend, --without=dev, --format=requirements.txt, --output=backend/requirements.txt]
      - id: poetry-export
        name: Export requirements-dev.txt
        args: [-C, ./backend, --only=dev, --format=requirements.txt, --output=backend/requirements-dev.txt]
